version: '3'

services:

    queue:
        image: "rabbitmq:3-management"
        ports:
        - "15672:15672"
        - "5672:5672"

    queue-processor:
        build: src/QueueProcessor/
        depends_on:
        - queue

    api:
        build: src/Api/
        depends_on:
        - queue
        ports:
        - "5000:80"