version: '3'

services:

    queue:
        image: "rabbitmq:3-management"
        ports:
        - "15672:15672"
        - "5672:5672"

    servicovisualizacao:
        build: src/servicoVisualizacao/
        depends_on:
        - queue

    api:
        build: src/api/
        depends_on:
        - queue
        ports:
        - "5000:80"