version: '3'

services:

    queue:
        build: src/Rabbitmq/
        ports:
        - "15672:15672"
        - "5672:5672"
        - "5552:5552"

    queue-processor:
        build: src/QueueProcessor/
        depends_on:
        - queue

    api:
        build: src/Api/
        depends_on:
        - queue
        ports:
        - "5000:80"